-- MySQL Script generated by MySQL Workbench
-- Tue Feb 15 23:23:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Blog_pessoal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Blog_pessoal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Blog_pessoal` DEFAULT CHARACTER SET utf8 ;
USE `Blog_pessoal` ;

-- -----------------------------------------------------
-- Table `Blog_pessoal`.`Tb_descricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blog_pessoal`.`Tb_descricao` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `Descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blog_pessoal`.`Tb_postagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blog_pessoal`.`Tb_postagens` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(255) NOT NULL,
  `Texto` VARCHAR(255) NOT NULL,
  `Data` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Blog_pessoal`.`Tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Blog_pessoal`.`Tb_usuarios` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `Senha` INT NULL,
  `Foto` VARCHAR(255) NULL,
  `Data_nascimento` VARCHAR(255) NOT NULL,
  `Tb_descricao_id` BIGINT NOT NULL,
  `Tb_postagens_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Tb_usuarios_Tb_descricao_idx` (`Tb_descricao_id` ASC) VISIBLE,
  INDEX `fk_Tb_usuarios_Tb_postagens1_idx` (`Tb_postagens_id` ASC) VISIBLE,
  CONSTRAINT `fk_Tb_usuarios_Tb_descricao`
    FOREIGN KEY (`Tb_descricao_id`)
    REFERENCES `Blog_pessoal`.`Tb_descricao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tb_usuarios_Tb_postagens1`
    FOREIGN KEY (`Tb_postagens_id`)
    REFERENCES `Blog_pessoal`.`Tb_postagens` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
